export const FlightData = [
  {
    id: 1,
    number: "C1C1C1",
    data: {
      plane: "Boeing 737",
      DEP: "Warsaw",
      ARR: "Athens",
      DEP_time: "16:40",
      ARR_time: "18:55",
    },
    passengers: [
      {
        id: 1,
        name: "Piotr Maniak",
        passport: "AAA111",
        seat: "",
        specServ: {},
      },
      {
        id: 2,
        name: "Gabriela Maniak",
        passport: "BBB111",
        seat: "7",
        specServ: {},
      },
      {
        id: 3,
        name: " Halina Maniak",
        passport: "CCC111",
        seat: "",
        specServ: { INF: true },
      },
      {
        id: 4,
        name: "Jerzy Maniak",
        passport: "DDD111",
        seat: "5",
        specServ: {},
      },
      {
        id: 5,
        name: "Sara Maniak",
        passport: "EEE111",
        seat: "2",
        specServ: { WHC: true },
      },
      {
        id: 6,
        name: "Mela Maniak",
        passport: "FFF111",
        seat: "12",
        specServ: {},
      },
      {
        id: 7,
        name: "Maciej Nowak",
        passport: "GGG111",
        seat: "",
        specServ: {},
      },
      {
        id: 8,
        name: "Marcin Stec",
        passport: "HHH111",
        seat: "55",
        specServ: {},
      },
    ],
  },
  {
    id: 2,
    number: "B12C36",
    data: {
      plane: "Boeing 737",
      DEP: "Warsaw",
      ARR: "Athens",
      DEP_time: "16:40",
      ARR_time: "18:55",
    },
    passengers: [
      {
        id: 1,
        name: "Piotr Maniak",
        passport: "AAA111",
        seat: "",
        specServ: {},
      },
      {
        id: 2,
        name: "Gabriela Maniak",
        passport: "BBB111",
        seat: "7",
        specServ: {},
      },
      {
        id: 3,
        name: " Halina Maniak",
        passport: "CCC111",
        seat: "",
        specServ: { INF: true },
      },
      {
        id: 4,
        name: "Jerzy Maniak",
        passport: "DDD111",
        seat: "5",
        specServ: {},
      },
      {
        id: 5,
        name: "Sara Maniak",
        passport: "EEE111",
        seat: "2",
        specServ: { WHC: true },
      },
      {
        id: 6,
        name: "Mela Maniak",
        passport: "FFF111",
        seat: "12",
        specServ: {},
      },
      {
        id: 7,
        name: "Maciej Nowak",
        passport: "GGG111",
        seat: "",
        specServ: {},
      },
      {
        id: 8,
        name: "Marcin Stec",
        passport: "HHH111",
        seat: "55",
        specServ: {},
      },
    ],
  },
];
